### ISSUE TITLE
Support request

### ISSUE THREAD

**Issue by welppee** [DevLARLEY/WidevineFetch#1]

**Comment by DevLARLEY** [comment]
I've tried Vudu before, but was never able to log into my account. 
FilmoTv seems to be a paid service, so you'll have to send me credentials if you want me to check if it's supported.

**Comment by DevLARLEY** [comment]
Have you tried it though? It should work on pretty much every service out of the box.

**Comment by welppee** [comment]
I looked trough the code and realized it wouldn't work but I decided to test it to be certain
I had to modify the script first to be compatible with Python 3.9 as the | operator isn't available in Python 3.9 and as I suspected
the script failed because Vudu uses websockets and Filmotv uses key iv and trows the error Could not parse license b\ i can share the credentials and a vpn if needed thanks in advance.

**Comment by welppee** [comment]
Below the changes to make it work with python 3.9 in case you want to add support for python versions below 3.10

the code change before  # is the code wich works and after # is the code wich doesnt work

from typing import Optional, Tuple, Union, List, Any, Dict # from typing import Any
def __init__(self, pssh: Optional[str], read: str): # def __init__(self, pssh: str | None, read: str):
def _parse(self) -> Optional[Tuple[str, Dict]]: # def _parse(self) -> tuple[str, dict] | None:
def _is_json(response: str) -> Optional[Any]: # def _is_json(response: str) -> Any | None:
def _substring_indices(content: Union[bytes, str], sub: Union[bytes, str]) -> List[int]: # def _substring_indices(content: bytes | str, sub: bytes | str) -> list[int]:
def _get_pssh(content: bytes) -> Optional[str]: # def _get_pssh(content: bytes) -> str | None:
def _extract_pssh(self,message: Union[str, bytes]) -> Optional[str]: # def _extract_pssh(self, message: str | bytes) -> str | None:
def _get_keys(self, url: str, headers: Dict, body: Any) -> Optional[List[str]]: # def _get_keys(self, url: str, headers: dict, body: Any) -> list[str] | None:

**Comment by DevLARLEY** [comment]
I'm sorry but I don't see the point in creating scripts for older versions of python while sacrificing readability and new pythonic features. That's what makes python so fun to code in

**Comment by DevLARLEY** [comment]
Is it possible to Copy a WebSocket Request as 'Copy as fetch'? I've never dealt with WebSockets before...
If yes, then I could imagine adding support for that.

**Comment by welppee** [comment]
> I'm sorry but I don't see the point in creating scripts for older versions of python while sacrificing readability and new pythonic features. That's exactly what makes python so fun to code in

Yeah thats fine i have to use python 3.9 since some packages do not work with newer python versions.

**Comment by welppee** [comment]
> Is it possible to Copy a WebSocket Request as 'Copy as fetch'? I've never dealt with WebSockets before... If yes, then I could imagine adding support for that.

I will check it out later thanks.
