### ISSUE TITLE
Can't WEB-DL live stream content!

### ISSUE THREAD

**Issue by Kh4N02** [DevLARLEY/WidevineFetch#11]
Hi bro, hope you are good 😄 

Were trying today after long time, as cricket content was broadcasted today on Amazon Prime Video Australia, tried to web-dl using this script but unfortunately giving some errors.. 

After I've entered the license as Fetch, in the command prompt it gave me this error:

Traceback (most recent call last):
  File "D:\Scripts\WidevineFetch-main\widevine-fetch.py", line 240, in run
    if keys := self._get_keys(
               ^^^^^^^^^^^^^^^
  File "D:\Scripts\WidevineFetch-main\widevine-fetch.py", line 457, in _get_keys
    if not (pssh := self.module.EXTRACT_PSSH(challenge, url, headers)):
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scripts\WidevineFetch-main\modules\amazon_480p.py", line 114, in extract_pssh
    return _extract_pssh(manifest_request.text)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Scripts\WidevineFetch-main\modules\amazon_480p.py", line 72, in _extract_pssh
    for content_protection in _ensure_list(ad_set["ContentProtection"]):
                                           ~~~~~~^^^^^^^^^^^^^^^^^^^^^
KeyError: 'ContentProtection'

Could you please help? Thanks 👍

**Comment by DevLARLEY** [comment]
can you post the manifest?

**Comment by Kh4N02** [comment]
Sorry for the delay, had issues with my prime account and couldn't login, fixed now.

The manifest that shows when I enter the license as Fetch in the script is:
https://jab.ll.ww.aiv-cdn.net/iad-nitro/jab-assets/jab-prod-iad/live/dash-sd/out/v1/968200c372ca4b96b004538042ebb41c/okvpfflfu3j5/cenc-sd-8765c5.mpd

The one that shows in the network tab using inspect elements is:
https://aivottjab-a.akamaihd.net/iad-nitro/jab-assets/jab-prod-iad/live/dash/out/v1/108bfdad52584b3dac8da45d0b679e7d/okvpfflfu3j5/cenc-bc1648.mpd?amznDtid=AOAGZA014O5RE&encoding=segmentBase

**Comment by DevLARLEY** [comment]
I updated the PSSH extraction mechanism, can you check again?

**Comment by Kh4N02** [comment]
Now it's working, thanks! Will download matches in 480p now. 😄❤️
