### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by Shy0o** [DevLARLEY/WidevineFetch#5]
SSLError: HTTPSConnectionPool(host='fwp.now.com', port=443): Max retries exceeded with url: /wrapperWV (Caused by SSLError(SSLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:1000)')))

Runtime error,Error report and crash

**Comment by Shy0o** [comment]
If you need account and password debugging, you can contact me.

**Comment by Shy0o** [comment]
https://nowplayer.now.com/liveplayer/332

https://news.now.com/home/live

It will be all right

**Comment by DevLARLEY** [comment]
I will take a look
