### ISSUE TITLE
vodafone license help

### ISSUE THREAD

**Issue by alienmaster9** [DevLARLEY/WidevineFetch#6]
Removed

**Comment by DevLARLEY** [comment]
Was WidevineFetch unable to get the keys at all or did it only work with your module?

**Comment by alienmaster9** [comment]
Was WidevineFetch unable to get the keys at all 

based on my request if you can make module which works with it will be helpful. @DevLARLEY

**Comment by DevLARLEY** [comment]
Does it work with WidevineFetch or not? If not, then what's the error you're getting?

**Comment by alienmaster9** [comment]
am getting signature error from request. i have blocked license url request used pssh as well.  but i am unable to get key error. any thing you can do it help to handle this

**Comment by DevLARLEY** [comment]
Post the error

**Comment by alienmaster9** [comment]
on browser reposne like this 
{
    "heartBeat": "300",
    "sessionToken": "i/QbLvKnfVI0CtKk3ZxiqH+NEJyKubl7ggSXUAECAOMqTeGV10FbnjbyocZX7csCRAMeJYWv7uq99fknckor846CjiMOYCcPa94hTyt8AotQU7mbt5u0Qm8Kyo2E8pRAmwuUFMVWheGeZ31yBpd5tLPUMs3n78GbFbgiC8Ab6eKU6hYmFG2jRe/Jjneezbxx3F88GaHRLH4o55VXCr0rlsoKbJoFTkZJtWdXLEFIDD+70P23ZMyk3hZa1dK9xvTzZBXDf8PULJX2imVprtS9ws4aRt2IyhXfKy5310jD4dEq+3ZHoxDbVIMmryk6/nBE1cqgv0DTpHGVqj6fp/Teme9InwQpI/8C+5HaoY58J9dHTA8Ms7TD7KqlmT4b3z6doRgfhsHJXybubDf+4i7LKUpFdBR4MEIervjFsKmcMet/K5hhErkxpGKjLhAGBY1ogHfcC5CzjKKXThAygLBX1EYkR9YnCF2nnqutQ2Rz7PcytckyCkGCSNNXXY8X2LDHyq/kAaL6eDJIXXwlIKG72DI3ZEpKsN+Gw8+0HnH6rNRzikkazB4ENRmOYKCeOKgHA5EZvZ+MZ9FgWLtCSDacwCvG8R6lnqFpuSfW2CaLhBM0ZQqwXjL6Ylatqk+HWKBL61v3uMhXULP/PzFoSKzYoLJNDwt4fGi4aEJPTfsJiRCtzB0ANpjdE5eJEvJGMdolzzzz3LahAa8=",
    "license": "CAISgQIKNAoQzKYWLmcKjw+tFYzOJbOVuBIQzKYWLmcKjw+tFYzOJbOVuBoAIAEoADgAQABI9f7stgYSEQgBEAAYASCkAzCkAzh4SKwCGlYSEOaPCcFtNs2J9OuY7QToETIaQPaOs0LMU8LKdUSdDLrBK/GnHafqmg6bqGZZVEbbouQPgq8z5Tq9VmJzj01J/itmiLD65KjkpXU1zqsJpQh2ZJcgARpUChD3sHRBLx1FS4FQgczpunUtEhCmEeFgKUhieHTL0DzQjxRXGhCq9A+hNlBtqZjE9ETfOfBBIAIoATICCAFCEgoQa2MxNgAAAaQR3rHlwAACDGIAIPX+7LYGOABQBRog53THe6QQOMAMPpblXMHMaceS3higcbqmX3salDPVGUoigAHL05Sr/tTuhJ5qpGPu0lXDTYpiBrAroDTSfKp/r4mR8QQYZ4ilwrt1Y2K/njv/qlEODJH1w/x/IBQ7UhzckbUgxGWLKTh07ZveAnc+plaBbQB3L7H5gbnIf2VzyWTkQvnlRMroF3L6X7CM7+Of7wXfGbOpdEz2lI5S+LIW/4AT5TozCjExOS4wLjYgQnVpbHQgb24gQXVnIDEyIDIwMjQgMTY6Mzc6MzIgKDE3MjM1MDU4NTIpQAFKsAEAAAACAAAAsAAFABAR3rHlevYcxAAAAE0AAAAQAAAAXwAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABAAAAAAAAAAAAAAAAAAAAAAAAAaQAAAAAAAAAAAAAAAAAAAGkAAAAAQAAAKUAAAAQAAAAtwAAABAAAADJAAAAEAAAAAAAAAAAAAAA5QAAABBIGXx1KkXzwD+WQGpO0VhPC7M4AnNFukctOzgUhAcrP1gB"
}

![image](https://github.com/user-attachments/assets/601e9d93-aa3b-4af9-9b13-0ba3606ba213)


i used block license and pssh but its still same.

**Comment by alienmaster9** [comment]
do you have discord or telegram i could share account with you so you can try your self.

**Comment by DevLARLEY** [comment]
@larley on discord

**Comment by alienmaster9** [comment]
added
