### ISSUE TITLE
Netflix video

### ISSUE THREAD

**Issue by deathnoragami** [DevLARLEY/WidevineFetch#9]
![image](https://github.com/user-attachments/assets/800f390a-8b1a-46e6-905a-60f99bc1bb4d)
Can I somehow get it with netlifx? I run the video, I even tried all post requests, but all of them had an error. There is only one file with the name license

**Comment by DevLARLEY** [comment]
Netflix is using a custom protocol called MSL, WidevineFetch (and any other program alike) will not work for Netflix.
